Canardoux/flutter_sound

- README.md
- ios/Classes/FlutterSoundPlugin.m
- lib/flutter_sound.dart
This allows setting sampleRate & numChannels for iOS (no effect on android, I don't know the apis there) without breaking compatibility with previous versions (parameters are optional, and default value keep the same behavior).
Also changes quality to max.
> merged improved 662d212 from https://github.com/Shigawire

- android/src/main/java/com/dooboolab/fluttersound/AudioInterface.java
- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- lib/flutter_sound.dart
Implementation of https://github.com/dooboolab/flutter_sound/pull/24 for Android
(numChannels & sampleRate)
> numChannels & sampleRate for Android

- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- lib/flutter_sound.dart
Fixing https://github.com/dooboolab/flutter_sound/issues/31
> Fixed Android Bug

- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- example/lib/main.dart
Before the seek would add the current millis to the new millis and not function properly. Commenting out the line that affects that works fine.
> Slider widget with seek

- example/lib/main.dart
> Fixed slider example.

- example/lib/main.dart
Showing wrong recorder time text when device timezone is different ( In minutes).
> Showing wrong recorder time text

- android/src/main/java/com/dooboolab/fluttersound/AudioInterface.java
- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- ios/Classes/FlutterSoundPlugin.m
- lib/android_encoder.dart
- lib/flutter_sound.dart
- lib/ios_quality.dart
- Add ability to specify Android encoder
- Add ability to specify iOS quality
> Android encoder and iOS quality settings

- CHANGELOG.md
- android/build.gradle
- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- ios/Classes/FlutterSoundPlugin.m
- pubspec.yaml
Reverts dooboolab/flutter_sound#63
This `PR` doesn't seem to work as expected.
> Revert "Android command queue for recording related tasks"

- CHANGELOG.md
- android/build.gradle
- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- ios/Classes/FlutterSoundPlugin.m
- pubspec.yaml
@hyochan This is the fixed version of #63.
The error in the original PR was caused by a missing "break;" statement in the `stopRecording` method handler. Classic...
> Android: Recording operations on a separate command queue.

- android/build.gradle
- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- lib/flutter_sound.dart
By resetting the mediaPlayer before releasing.
> Fixed 'mediaplayer went away with unhandled events'  bug

- README.md
- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- example/lib/main.dart
- lib/flutter_sound.dart
The db calcs were constantly saturating at 160db even with a low volume recording.
Also fixed some state inconsistency with method callbacks.
Improved some the exceptions been thrown.
> Improved db calcs.

- CHANGELOG.md
- example/lib/main.dart
- ios/Classes/FlutterSoundPlugin.m
- pubspec.yaml
- Resolve few issues on `ios` record path.
- Resolve issue `playing` status so player can resume.
- Resolve [#134](https://github.com/dooboolab/flutter_sound/issues/134).
- Resolve [#135](https://github.com/dooboolab/flutter_sound/issues/135).
> Release 1.4.7

- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- example/lib/main.dart
Resolve #221 
- Use app specific path - https://developer.android.com/training/data-storage/app-specific
> Fix android path to be appended

- lib/flauto.dart
- lib/flutter_sound.dart
- lib/flutter_sound_player.dart
- lib/flutter_sound_recorder.dart
- pubspec.yaml
I have updated the startRecorder method to be compatible with permission_handler: 5.x.x. And removed unnecessary imports.
> flixed conflic with permission_handler 5.x.x

- README.md
- example/android/build.gradle
- lib/src/plugins/sound_recorder_plugin.dart
- lib/src/sound_player.dart
- lib/src/sound_recorder.dart
- lib/src/util/recording_disposition_manager.dart
> Updated read.me migration notes. Hid some more internal apis.

- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundRecorder.java
Record/Playback tested after simply add this list item.
> fix issue #380 in main repo

- doc/ui_widget.md
Its a start. More to add later.
> More documentation for SoundPlayerUI Widget

- pubspec.yaml
recase version is preventing us updating other libraries.
Thank you for this library, we will try to make more contributions in future
> update recase version

- flutter_sound/lib/src/ui/sound_recorder_ui.dart
Adding the support of external titles for the recording states, to support the other languages instead of the English only.
> Edits in SoundRecorderUI

- flutter_sound_web/js/flutter_sound/flutter_sound_recorder.js
The values that are set to the analyser still needs to be checked.
I tried to set it so its behaviour could be as close as possible to that of android.
> Added read decibel value from recorder on web

- flutter_sound/ios/Classes/FlutterSoundPlayer.mm
- flutter_sound/lib/public/flutter_sound_player.dart
- flutter_sound_platform_interface/lib/flutter_sound_player_platform_interface.dart
- flutter_sound_platform_interface/lib/method_channel_flutter_sound_player.dart
- flutter_sound_web/lib/flutter_sound_player_web.dart
[Linked](https://github.com/Canardoux/flutter_sound_core/pull/4)
While developing a VoIP app I noticed that the audio was too low. After some research I see that activating the VoiceProcessingIO AudioUnit will improve the speech audio a lot, so I added the function to this lib.
I'm not sure if this is possible on Android but I will investigate it as well soon.
> VoiceProcessing feature for iOS

- doc/pages/guides/guides_getting-started.md
Corrected the method names for open and close in the example using FlutterSoundRecorder.
> Fix incorrect method names in the doc

- doc/pages/guides/guides_getting-started.md
- doc/pages/tau-sound/install.md
Description: This PR updates the Installation section of the Flutter Sound documentation to include essential setup instructions for iOS recording functionality. Key changes include:
This update Adds guidance on adding the audio_session dependency for iOS recording setup, providing users with clear steps to configure audio sessions required for recording on iOS devices.
Enhances structure and readability of the installation instructions to support easier integration directly from pub.dev.
This update will help developers follow all necessary configuration steps, especially for recording on iOS. Let me know if further adjustments are needed.
Additional Notes:
No methods or functions were added; the update is limited to dependency and setup documentation.
> Update Installation Guide with Additional iOS Setup for Recording

- flutter_sound/CHANGELOG.md
- flutter_sound/android/src/main/java/xyz/canardoux/fluttersound/FlutterSound.java
- flutter_sound/pubspec.yaml
Reverts Canardoux/flutter_sound#1116
> Revert "Removes v1 Flutter Android embedding references"
