- example/lib/main.dart
- example/test/unit_test.dart
I added an example audio source that comes from my Google Firebase Storage so we can see a working demonstration to test the seeker and other player controls. The seeker works fine, you're able to press or drag anywhere in the seeker to go to that song's position. The seeker now fills the container's width, too. The onChanged property takes in a double value, which is the new value that the user has pressed or dragged to, and we use that value to seek the player to that new value, and that is why we have to convert it to an int, because flutterSound.seekToPlayer method takes an int value to seek.
> working_seeker_with_audio_example

- ios/Classes/FlutterSoundPlugin.m
Android startPlayer/startRecorder assumes the given URI is absolute, while iOS assumes the URI is relative to the temporary directory. In practice this means that a valid full path given to Android would not work on iOS. This changes iOS to interpret given URIs as full paths.
E.g. passing the URI
```
/<path_to_app>/Documents/recordings/file.m4a
```
Gets translated to the (invalid, notice the double slash `"//"` and the repeated `<path_to_app>`) URI in iOS
```
/<path_to_app>/tmp//<path_to_app>/Documents/recordings/file.m4a
```
> Fix file URI for recording and playing in iOS

- android/src/main/java/com/dooboolab/fluttersound/AudioInterface.java
- android/src/main/java/com/dooboolab/fluttersound/AudioModel.java
- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- ios/Classes/FlutterSoundPlugin.m
- lib/flutter_sound.dart
This PR implements bitRate customisation for both Android/iOS targets. This is particularly useful for Android where the default bitrate is very low (poor quality).
I also renamed the default android extension from .**mp4** to .**m4a** since this is the recommended for MPEG-4 audio files and it now matches iOS.
> Allow BitRate customisation

- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- example/lib/main.dart
- ios/Classes/FlutterSoundPlugin.m
Also adjusted the dbPeak range (to 0-160)
> Fix: bitRate nullability check for iOS was wrong and throwing an exception when bitRate was not specified

- CHANGELOG.md
- android/build.gradle
- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- ios/Classes/FlutterSoundPlugin.m
- pubspec.yaml
This adds a single threaded command queue fo all recording commands on Android (start/stop) as this could have caused interference when users started/stopped recording very quickly.
The PR also contains a few other changes to the build environment and removes a bit of dead code.
@hyochan please let me know if you'd like these changes in a separate set of PRs.
Fixes: #53, #61
> Android command queue for recording related tasks

- ios/Classes/FlutterSoundPlugin.m
`seekToPlayer` on Android returns a String, and on iOS was returning an int. This is reflected in Issue #70. This PR fixes that, making iOS match the Android behaviour.
The iOS `AVAudioPlayer` class's `currentTime` property is measured in seconds instead of milliseconds. This PR converts milliseconds into seconds when setting the current time in the `seekToPlayer` function.
Additionally, the `seekToPlayer` function wasn't calling the `updateProgress` Dart method, which was happening on Android. This PR also adds equivalent functionality to iOS.
> iOS: Fixes for seekToPlayer 

- ios/Classes/FlutterSoundPlugin.m
This is a small change but a very useful configuration on iOS side that will allow the user to capture a bluetooth-headset microphone stream audio when its paired with the phone and set as default input.
If user doesn't have a paired headset, it will work normally using the internal microphone as expected.
> iOS: Setup configuration for using bluetooth microphone recording input

- CHANGELOG.md
- android/build.gradle
- example/android/app/build.gradle
- pubspec.yaml
This PR essentially increases compile & minSDK version to 28 and removes unused references to legacy test runners, which in turn is enough to ensure AndroidX compatibility.
Nonetheless tests should be created for this project at some stage. :-)
@hyochan pub version & change log already updated - you can release once merged.
> AndroidX compatibility improved

- example/lib/main.dart
`seekToPlayer()` takes milliseconds as input on iOS now. We can remove this conditional check from the example because it is no longer valid.
> fix(example): remove milliseconds conversion

- README.md
Updates to the doco detailing how to correctly dispose of the player/recorder when you widget is detached.
Also provide details on correct usage of the returned futures to ensure the player is correctly initialised before you attempt any operations on it.
> Updated readme with details on disposing player/recorder

- .gitignore
- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- example/lib/main.dart
- lib/flutter_sound.dart
Added check for a maxAmplitude of zero which can happen if the mic is off which was resulting in db being set to infinity. Db is now set to zero.
This problem may only be an issue with the simulator, but its annoying enough in development that this simple fix is warrented.
This pull also includes some code cleanup to remove a number of lint warnings.
> Stopped recording generating infinite db values.

- ios/Classes/FlutterSoundPlugin.m
Fix iOS build error when used in conjunction with path_provider and other libs ( #146 ) defining their own `GetDirectoryOfType `.
Postfix `GetDirectoryOfType` fn to avoid conflict with other libs.
> Fix #146 - refactor: postfix GetDirectoryOfType to avoid conflicts

- CHANGELOG.md
- README.md
- android/src/main/java/com/dooboolab/fluttersound/AudioInterface.java
- android/src/main/java/com/dooboolab/fluttersound/AudioModel.java
- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
- example/ios/Podfile.lock
- example/lib/main.dart
- ios/Classes/FlutterSoundPlugin.m
- lib/android_encoder.dart
- lib/flutter_sound.dart
- pubspec.yaml
1.6.0
+ Set android default encoding option to `AAC`.
+ Fix android default poor sound.
- Resolve [#155](https://github.com/dooboolab/flutter_sound/issues/155)
- Resolve [#95](https://github.com/dooboolab/flutter_sound/issues/95)
- Resolve [#75](https://github.com/dooboolab/flutter_sound/issues/79)+ Set android default encoding option to `AAC`.
+ Fix android default poor sound.
- Resolve [#155](https://github.com/dooboolab/flutter_sound/issues/155)
- Resolve [#95](https://github.com/dooboolab/flutter_sound/issues/95)
- Resolve [#75](https://github.com/dooboolab/flutter_sound/issues/79)
> [Release] Make ios & android audio format compatible by default

- ios/Classes/FlutterSoundPlugin.m
Actually it returns the absolute string of a so called file URL which starts with `file:///`. This isn't a POSIX compliant file path which always starts with a slash `/`.
The Android version of this plugin returns the result of `getPath` which gives us a POSIX compliant path, too.
@hyochan It would be very nice to have this PR in a current release of the plugin as soon as possible. Actually we are working with our fixed fork, which we would like to get rid of. Thanks a lot!
> Fixes returned filePath on iOS

- android/build.gradle
- example/android/app/build.gradle
Android MinSdkVersion is 22 instead of 23. SDK prior to 22 crashes on recorder.stop().
Issue: minsdk 23 [question] #174
> Android minSdkVersion is 22 instead of 23. SDK before 22 fails

- lib/flutter_sound.dart
Apparently IOS volume is scored out of 100, this fix reduces documentation and keeps the platform details hidden.
> Fix for Bug #128

- android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
At the moment we use MPEG-4 as format for android recordings and AAC LC for ios recordings. This PR sets AAC LC as default for AAC recordings under android to have the same formats as under ios.
This may be breaking.
> Use AAC-LC format instead of MPEG-4

- README.md
The README file says that you should enter
ext.flutterFFmpegPackage = 'audio-lts' on the pubspec.yaml,
when in reality, it should be into the android/gradle.build file.
> Fix error on documentation for Android FFmpeg setup

- lib/flutter_sound_recorder.dart
To avoid permission_handler unable to detect current activity error in foreground service, we should get permission outside of the service.
> Added requestPermission argument with default value true

- ios/Classes/Track.m
Was previously being assigned from albumArtAssetString, clearly that stanza copied and incompletely edited into this one!
Spotted by Xcode ;)
> Correct copy/paste albumArtFile assignment error

- flutter_sound/lib/src/util/log.dart
- flutter_sound/pubspec.yaml
Signed-off-by: Ayush P Gupta <ayushpguptaapg@gmail.com>
Currently i am using logger package in one of library in main project but due to old logger version in flutter_sound, it cause error of mismatch version
> Update logger package to ^0.9.4

- tau_core/web/js/flutter_sound/flutter_sound_recorder.js
This will close mediaStream properly and remove recording icon when there's no active recording.
fixes #655
> Stop mediaStream tracks after recording ends.

- doc/CHANGELOG.md
- flutter_sound/ios/Classes/FlutterSoundPlayerManager.mm
This is a workaround to fix crash #642.
I just added a return statement before we reach the code that crashes.
So far it seems that my app doesn't crash when I use it along just_audio.
> Fix crash #642

- doc/pages/the-tau-project/tau_dev.md
If someone doesn't have SSH keys configured with GitHub, the command would fail so prefer URL instead. Maybe the docs should include instructions to fork the project and clone that fork instead; open for discussion.
> Update dev docs to use URL instead of SSH for git clone command

- flutter_sound/lib/public/flutter_sound_recorder.dart
The only problem is when using `Codec.defaultCodec` I'm not sure how to determine what codec the system decided to use. If you choose 'Codec.mp3' you get a `_CodecNotSupportedException` exception, but if you use the default codec with .mp3 file extension, it works fine.
I need a way to get the codec being used by the OS before calling the new `isValidFileExtension` method so we can handle cases that use `Codec.defaultCodec`. I don't know how to do that, any advice is welcome
> Check for valid file extension based on audio codec

- flutter_sound/lib/public/ui/recorder_playback_controller.dart
- flutter_sound/lib/public/ui/sound_player_ui.dart
- flutter_sound/lib/public/ui/sound_recorder_ui.dart
Not a complete set of fixes, but corrects the most glaring issues with the widget UI. If you create a RecorderPlaybackController with both a recorder and a player, the recorder is now disabled when the player is playing, which heads off a bunch of potential error states. Similarly, when recording the player is disabled. 
The widget UI still has a number of incomplete features but the basic functions now work consistently. Still needs a proper maintainer but this should keep it functional for a bit.
> Basic fixes to widget UI

- flutter_sound/lib/public/flutter_sound_recorder.dart
I noticed `xyz.canardoux.flutter_sound_bgservice` was not being invoked when `openRecorder()` was called but is being invoked for `openPlayer()`, which let to issues when trying to run it in the background. This PR adds it.
> Add isBGService to openRecorder

- flutter_sound/CHANGELOG.md
- flutter_sound/android/src/main/java/xyz/canardoux/fluttersound/FlutterSound.java
- flutter_sound/pubspec.yaml
Fixes https://github.com/Canardoux/flutter_sound/issues/1065.
Tested by building the flutter_sound example app with the changes in https://github.com/flutter/engine/pull/52022 applied.
> Removes v1 Flutter Android embedding references
